[package]
name = "minter-contract-utils"
version.workspace = true
edition.workspace = true

[features]
test-contracts = []

[dependencies]
anyhow = { workspace = true }
candid = { workspace = true }
did = { workspace = true }
eth-signer = { workspace = true }
ethers-core = { workspace = true }
ethereum-json-rpc-client = { workspace = true, features = [
    "ic-canister-client",
    "http-outcall",
] }
hex = { workspace = true }
ic-canister-client = { workspace = true }
ic-stable-structures = { workspace = true }
jsonrpc-core = { workspace = true }
minter-did = { workspace = true }
once_cell = { workspace = true }
serde = { workspace = true }

[build-dependencies]
solidity-helper = { path = "../solidity-helper" }
anyhow = { workspace = true }

[dev-dependencies]
candid = { workspace = true }
ic-exports = { workspace = true }
solidity-helper = { path = "../solidity-helper" }
